### ISSUE TITLE
How to download ‘custom OVMF’ source

### ISSUE THREAD

**Issue by adofirst2018** [intel/nemu#100]
I follow this guidance [(https://gist.github.com/sameo/51dc5556714c09a7a52163522114e2dd)](url)
download custom ‘custom OVMF’， I want to know how to download ‘custom OVMF’ source？

**Comment by sameo** [comment]
@duhongyu The custom OVMF code for supporting the i386/virt platform is here:

https://github.com/rbradford/edk2

**Comment by rbradford** [comment]
@duhongyu There are also binaries built by travis available here: https://github.com/rbradford/edk2/releases

**Comment by adofirst2018** [comment]
@sameo @rbradford thanks very much，
