### ISSUE TITLE
NEMU boot time is looger than qemu

### ISSUE THREAD

**Issue by adofirst2018** [intel/nemu#101]
I start ubuntu cloud 16.04 with NEMU, but boot time is 19s, even looger than qemu-2.9， It takes about 13s from start NEMU command to print ‘loop: module loaded’.

/tmp/debug_log show 
it take about 13s wait print "MpInitChangeApLoopCallback() done!" after print "FSOpen: Open '\EFI\BOOT\grubx64.efi' Success"  

this is start NEMU command:

/home/duhy/workSpace/nemu/nemu/build-x86-64/x86_64-softmmu/qemu-system-x86_64 \
            -bios /home/duhy/workSpace/nemu/OVMF.fd \
            -nographic -nodefaults -L . -net none \
            -machine virt,accel=kvm,kernel_irqchip \
            -cpu host -m 512,slots=4,maxmem=16950M \
            -smp 2 \
            -device sysbus-debugcon,iobase=0x402,chardev=debugcon \
            -chardev file,path=/tmp/debug-log,id=debugcon \
            -device sysbus-debugcon,iobase=0x3f8,chardev=serialcon \
            -chardev file,path=/tmp/serial-log,id=serialcon \
            -device virtio-blk-pci,drive=image \
            -drive if=none,id=image,file=/home/duhy/workSpace/nemu/xenial-server-cloudimg-amd64-uefi1.img \
            -device virtio-blk-pci,drive=seed \
            -drive if=none,id=seed,file=/tmp/seed.img,format=raw \
            -device virtio-serial-pci,id=virtio-serial0 \
            -device virtconsole,chardev=charconsole0,id=console0 \
            -chardev stdio,id=charconsole0 \
            -netdev tap,id=mynet0,ifname=tap0,script=no,downscript=no \
            -device virtio-net-pci,netdev=mynet0

this is start qemu command：

/usr/libexec/qemu-kvm \
            -nographic -net none \
            -machine pc,accel=kvm,kernel_irqchip \
            -cpu host -m 512,slots=4,maxmem=16950M \
            -smp 2 \
            -device virtio-blk-pci,drive=image \
            -drive if=none,id=image,file=/home/duhy/workSpace/nemu/xenial-server-cloudimg-amd64-uefi1.img \
            -device virtio-blk-pci,drive=seed \
            -drive if=none,id=seed,file=/tmp/seed.img,format=raw \
            -netdev tap,id=mynet0,ifname=tap0,script=no,downscript=no \
            -device virtio-net-pci,netdev=mynet0

**Comment by yangzhon** [comment]
@duhongyu 

please use pure virt build and check again, the config file ref tools/build_x86_64_virt.sh, thanks!

below is my qemu command for you ref:
sudo /home/chen/nemu/build/x86_64_virt-softmmu/qemu-system-x86_64_virt \
     -bios /home/chen/Downloads/OVMF_0.2.fd \
     -nographic \
     -nodefaults \
     -L . \
     -machine virt,accel=kvm,kernel_irqchip \
     -smp sockets=1,cpus=4,cores=2,maxcpus=8 -cpu host \
     -m 512 \
     -device sysbus-debugcon,iobase=0x402,chardev=debugcon -chardev file,path=/tmp/debug-log,id=debugcon \
     -device virtio-blk-pci,drive=image -drive if=none,id=image,file=/home/chen/Downloads/clear-24380-cloud.img \
     -device virtio-serial-pci,id=virtio-serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev stdio,id=charconsole0 \
     -monitor telnet:127.0.0.1:55555,server,nowait

**Comment by yangzhon** [comment]
@duhongyu

This issue is also found in PC or Q35 platform with same qemu command?

**Comment by adofirst2018** [comment]
[root@duhy nemu]# /home/duhy/workSpace/nemu/nemu/build-x86-64/x86_64-softmmu/qemu-system-x86_64 -machine help
Supported machines are:
pc                   Standard PC (i440FX + PIIX, 1996) (alias of pc-i440fx-3.0)
....
q35                  Standard PC (Q35 + ICH9, 2009) (alias of pc-q35-3.0)
pc-q35-3.0           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.9           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.8           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.7           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.6           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.5           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.4           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.12          Standard PC (Q35 + ICH9, 2009)
pc-q35-2.11          Standard PC (Q35 + ICH9, 2009)
pc-q35-2.10          Standard PC (Q35 + ICH9, 2009)
virt                 QEMU 3.0 i386 Virtual Machine (alias of virt-3.0)
virt-3.0             QEMU 3.0 i386 Virtual Machine
virt-2.12            QEMU 2.12 i386 Virtual Machine

**Comment by adofirst2018** [comment]
@yangzhon what is your gcc version?

**Comment by yangzhon** [comment]
@duhongyu 

gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)

**Comment by adofirst2018** [comment]
@yangzhon thanks, my gcc version is low,  there is some error at compile nemu

**Comment by rbradford** [comment]
@duhongyu For the xenial image, did you modify the kernel command line: e.g. 

```
 sudo guestmount -i -a ~/workloads/xenial-server-cloudimg-amd64-uefi1.img /mnt
 sudo sed -i "s/console=tty1 console=ttyS0/console=tty1 console=ttyS0 console=hvc0/" /mnt/boot/grub/grub.cfg
 sudo umount /mnt
```

?

**Comment by adofirst2018** [comment]
@rbradford I have modify /mnt/boot/grub/grub.cfg follow your guidance，my compile nemu target is ‘qemu-system-x86_64’， is this lead to the issue?  should I compile target is 'qemu-system-x86_64_virt '?

**Comment by rbradford** [comment]
@duhongyu Thank you. I asked because I have observed that not changing grub.cfg can result in boot delays.

I think we need to understand where the delays are coming from. Is it firmware, kernel or userspace time. Your remark:

> it take about 13s wait print "MpInitChangeApLoopCallback() done!" after print "FSOpen: Open '\EFI\BOOT\grubx64.efi' Success"

Makes me think it could be a combination of grub and the kernel as that function you mention is hooked into `ExitBootServices()`. Changing to a pure virt build is unlikely to have any impact.

**Comment by adofirst2018** [comment]
@rbradford thanks,  I think mainly boot time take in fireware(EDK2.0),  have you this problem?

**Comment by rbradford** [comment]
@duhongyu I don't think so. You said that it took 13s between "FSOpen: Open '\EFI\BOOT\grubx64.efi and "MpInitChangeApLoopCallback() done"

That is not firmware time. That is GRUB (and depending on how it is loaded) Linux time.

**Comment by adofirst2018** [comment]
@rbradford thanks，your answer is right,  can you give me some advise, how to debug this issue?

**Comment by gssxd** [comment]
> @duhongyu I don't think so. You said that it took 13s between "FSOpen: Open '\EFI\BOOT\grubx64.efi and "MpInitChangeApLoopCallback() done"
> 
> That is not firmware time. That is GRUB (and depending on how it is loaded) Linux time.

@rbradford 
In /mnt/boot/grub/grub.cfg, I comment out #123 line as below, the ubuntu can fast boot into login.
`#search --no-floppy --fs-uuid --set=root`

I found in /mnt/boot/efi/boot/grub/grub.cfg it has done the gpt partition search, I think no need to do search again in /mnt/boot/grub/grub.cfg(maybe it was trying to search a MBR disk)
`search.fs_uuid 70fd7baa-e7fd-4cb6-b80d-92cf423689f1 root hd0,gpt1`

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
