### ISSUE TITLE
Add nemu-specific tag to "--version" output

### ISSUE THREAD

**Issue by jodh-intel** [intel/nemu#127]
To allow users to determine if their qemu binary is in fact NEMU, please add a unique tag (`nemu`? :-) to the output of `--version`.

This will be particularly useful when [Kata Containers are configured to use NEMU](https://github.com/kata-containers/documentation/pull/266) since running `kata-runtime kata-env` will then capture this important detail to determine which version of QEMU is being used regardless of the binary name.

/cc @sboeuf.

**Comment by sboeuf** [comment]
Thanks @jodh-intel
@sameo @rbradford what do you think about this? This would make nemu identification clear.

**Comment by sameo** [comment]
PR #131 fixed that one.
