### ISSUE TITLE
SMBIOS for virt 

### ISSUE THREAD

**Issue by liujing2** [intel/nemu#129]
@sameo @rbradford @yangzhon @mcastelino 
Two key points in conclustion.
1. Do we need open CONFIG_SMBIOS for virt platform in order to use DMI?
1. If yes, there're 2 sub issues.
    1. CONFIG_SMBIOS=y is set in default-configs/x86_64-softmmu.mak, but actually when hw/i386/fw.c fw_build_smbios() check it, it doesn't show as expect. So Nemu doesn't build smbios tables for guest and dmesg shows [    0.000000] DMI not present or invalid.
    1. After fixing i by workaround, only q35 guest can show correct DMI dmesg, virt still shows [    0.000000] DMI not present or invalid.

**Comment by liujing2** [comment]
Some answers as below.

1. @mcastelino mentioned some reasons for DMI in IRC.
```
<mrcastel> the next issue we need to figure out is why DMI info is not passed to Linux for virt
<mrcastel> DMI info is sent in properly by QEMU/ovmf to Linux for q35 and pc
<mrcastel> we have made some mistake in QEMU or ovmf that prevents it
<mrcastel> THe DMI issue is that the kernel says
<mrcastel> [    0.000000] DMI not present or invalid
<mrcastel> for the virt platform
<mrcastel> the DMI not present is there for both virt and Q35 with nemu
<mrcastel> but in normal qemu and ovmf the DMI information is present
<mrcastel> we need to figure out what code change we did caused the DMI info to disappear
<mrcastel> we need the DMI tables to be setup for segments to work
<mrcastel> if you boot mainline QEMU and OVMF you will see DMI present with Q35
<mrcastel> with our nemu we do not see it with Q35 or virt
<mrcastel> we need to figure out why
<mrcastel> so we broke DMI support somewhere
```

And mails mentioned by @mcastelino 
>We will need a simplified code just to report minimal DMI. Just platform name and date. If not the Linux kernel assumes that it is on a really old bios and disables fine features. 

>Let me look at the minimal requirements we need to report. 


2. If we need open CONFIG_SMBIOS, two sub-issues.
For the first one, @yangzhon has root caused as follows.
>As for DMI in Q35 machine type in NEMU repo, this issue is clear now.

> I added CONFIG_SMBIOS in fw_build_smbios in commit id(84d425aee)

> The file hw/i386/fw.c is obj build, but the previous smbios is common-obj build
>ifeq ($(CONFIG_SMBIOS),y)
>common-obj-y += smbios.o
>#endif

>The fw.o and smbios.o in different location, If I add CONFIG_SMBIOS=y in host makefile, the DMI can > work in Q35 in NEMU. 

For the second, once we open the config, some default values for smbios need to be set firstly. Otherwise, Nemu could not build tables for guest. @liujing2 send [PR](https://github.com/intel/nemu/pull/128) to fix that.

**Comment by sameo** [comment]
@liujing2 Could you please clarify why we need DMI and SMBIOS?

**Comment by liujing2** [comment]
@sameo I updated information above. 

And mails mentioned by @mcastelino

>We will need a simplified code just to report minimal DMI. Just platform name and date. If not the Linux kernel assumes that it is on a really old bios and disables fine features.

>Let me look at the minimal requirements we need to report.

Actually, both Yang and I are not sure why and just quickly align with Manohar this morning. So maybe we could ask later for details?

**Comment by rbradford** [comment]
Users of `dmi_get_date()` that might be relevant to us

```
arch/x86/pci/acpi.c:    if (dmi_get_date(DMI_BIOS_DATE, &year, NULL, NULL) && year < 2008) {
arch/x86/pci/direct.c:  dmi_get_date(DMI_BIOS_DATE, &year, NULL, NULL);
arch/x86/pci/mmconfig-shared.c:         if (dmi_get_date(DMI_BIOS_DATE, &year, NULL, NULL) &&
drivers/pci/pci.c:              if (dmi_get_date(DMI_BIOS_DATE, &year, NULL, NULL) &&
```

The first can be overriden by pci=use_crs on the kernel command line but it **seems we are using the values from ACPI anyway** "[    0.293202] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug"

The second generates a warning that **we don't see**  "PCI: Sanity check failed"

The third generates a warning **that does not appear** about MCFG region.

The fourth one is only about D3 power management on PCIe ports which is not relevant for us.

**Comment by yangzhon** [comment]
Why DMI need SMBIOS ? In QEMU
fw_build_smbios() ----> smbios_get_tables()----->smbios_entry_point_setup(), which will create DMI entry point

In the upstreamed QEMU, the Guest will show below info:
/sys/firmware/dmi/tables/smbios_entry_point

**Comment by mcastelino** [comment]
The main reason for us to just report a minimal DMI info is to allow MCFG above 4GB. This allows the MCFG to be allocated anywhere it fits best without requiring a kernel change. 

[x86/PCI: allow MMCONFIG above 4GB](https://github.com/torvalds/linux/commit/9a08f7d)
```
x86/PCI: allow MMCONFIG above 4GB

The current whitelist requires a kernel change for every machine that has
MMCONFIG regions above 4GB, even if BIOS provides a correct MCFG table.

This patch expands the whitelist to include machines with a rev 1 or newer
MCFG table and a DMI_BIOS_DATE of 2010 or later.  That way, we only need
kernel changes for new machines that provide incorrect MCFG tables.
```

**Comment by mcastelino** [comment]
Expanding on this issue further, today if MCFG area was allocated above 4GB and communicated via the ACPI tables, the kernel will not be able to use this due to the DMI check. The DMI check was introduced to work around broken BIOSes. This allows the virt platform to place the MCFG area in any location.

Also in the future it allows PCI Segment MCFG's to be placed above 4GB which gives us considerable amount of flexibility.

**Comment by rbradford** [comment]
What about fixing it in the kernel? We already need a kernel patch to be able do hotplug.

As we can currently get by without having the MCFG allocated above 4GiB it feels inappropriate to add a legacy feature just to appease some code that is a workaround for detecting we're not a broken bios. Instead we should look at how we can patch the kernel to accept the virt machine.

e.g. currently it checks if the oem_id in the header is "SGI" we could also add a patch that checks if it matches NEMU's oem_id

https://github.com/torvalds/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/arch/x86/pci/mmconfig-shared.c#L553

**Comment by mcastelino** [comment]
@rbradford yes patching the kernel is an option and the right one going forward. 

The only reason to have the DMI info reported is to support older kernels and distros. We know that linux has supported PCI segments for a while and we can support multiple segments today using virt without a kernel change.

**Comment by liujing2** [comment]
@mcastelino  So if we give a DMI_BIOS_DATE after 2010, we could use MCFG above 4g, right? For the previous experiment, you set MCFG located as 0x60000000.

And other question is, besides the year info, what else is needed in the DMI build?

**Comment by sameo** [comment]
> The only reason to have the DMI info reported is to support older kernels and distros. 

@mcastelino Have we identified which other parts of the kernel would expect to get DMI information from us? And would the kernel need something else than a BIOS year?

**Comment by sameo** [comment]
> e.g. currently it checks if the oem_id in the header is "SGI" we could also add a patch that checks if it matches NEMU's oem_id

@rbradford Or have a kernel parameter to completely disable that check and avoid changing the kernel for each OEM ID that does not need to check this.

**Comment by rbradford** [comment]
We agreed that we don't need to reintroduce DMI/SMBIOS as we can instead reduce the < 4GiB lowmem range in order to fit all the MMCONFIG allocations needed to support a reasonable number of PCI segments and host bridges on them.
