### ISSUE TITLE
Documentation: Describe VFIO testing with NEMU

### ISSUE THREAD

**Issue by mcastelino** [intel/nemu#137]
VFIO testing with NEMU is manual. The initial cut of the documentation on how to perform the same using a GPU is described here. Please review. We will add additional devices which have simpler VFIO setup.

https://github.com/intel/nemu/wiki/Testing-VFIO

**Comment by liujing2** [comment]
@mcastelino  I have a question that, if we want to use one GPU for guest passthrough, why do we need bind it to vfio-pci when host boot up, in other words, why could not unbind and bind to vfio-pci after boot? Thanks.

**Comment by mcastelino** [comment]
> @mcastelino I have a question that, if we want to use one GPU for guest passthrough, why do we need bind it to vfio-pci when host boot up, in other words, why could not unbind and bind to vfio-pci after boot? Thanks.

@liujing2 for all other devices you can unbind at runtime. For the GPU you have to blacklist the driver. Runtime unbind does not work. Also early binding to vfio does not work either. Would you mind adding a section to the wiki explaining VFIO with other devices.

**Comment by liujing2** [comment]
@mcastelino Got it. I used to manually remove the driver module under /lib/ to unbind at runtime. This might be a tough way. 
OK, I will add a section for the VFIO tests with other devices.

**Comment by liujing2** [comment]
@mcastelino Draft a document for NIC in the wiki.

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
