### ISSUE TITLE
Several questions about nemu's development

### ISSUE THREAD

**Issue by terenceli** [intel/nemu#157]
Hello all,

Here I have some questions about nemu's development status.
1. As the README says, it only for kvm, but why there contains the TCG code?
2. Is the no-related arch/file or some others removed over, or still in progress, do you 
still accept the PR such as removing the unrelated things?
3. Where goes the discussion about some more concrete features, such as I don't know why the vnc
is not enable by default?

Thanks,
Li Qiang

**Comment by lkml-likexu** [comment]
The Tiny Code Generator (TCG) exists to transform target insns (the processor being emulated) via the TCG frontend to TCG ops which are then transformed into host insns (the processor executing QEMU itself) via the TCG backend. 

People who wish to port QEMU to run on a new processor need to be concerned with the backend. There also exists the TCI (TCG Interpreter) effort which provides a backend agnostic interpreter for TCGops. 

People who wish to port QEMU to emulate a new processor need to be concerned with the frontend.

**Comment by liujing2** [comment]
@terenceli  Thanks for reading the project. For the detailed questions, it is good to post here and we will give attention and feedback.

**Comment by yangzhon** [comment]
@terenceli 

1. The TCG code is in QEMU. The initial QEMU only supported TCG model and when KVM module in kernel was ready, and Avi enabled KVM accelactor in QEMU.

2. We made some features and hw/ configurable, anyway, any features configurable is welcome and please send the PR    

3. If you have some issues, please list the issues in github. As for VNC feature, we default disable it in the shell script, if you need it, you can remove this in ./tools/build_*.sh

**Comment by terenceli** [comment]
@yangzhon 
> @terenceli
> 
> 1. The TCG code is in QEMU. The initial QEMU only supported TCG model and when KVM module in kernel was ready, and Avi enabled KVM accelactor in QEMU.

Indeed, but IIUC the kvm VM doesn't depend TCG anyway. Also the TCG is for emulation, As nemu is 
abbreviation for No Emulation, I think TCG can cut off totally.

> 2. We made some features and hw/ configurable, anyway, any features configurable is welcome and please send the PR
> 3. If you have some issues, please list the issues in github. As for VNC feature, we default disable it in the shell script, if you need it, you can remove this in ./tools/build_*.sh

**Comment by yangzhon** [comment]
@terenceli

TCG are all compiled out from binaries, including x86 and ARM.

**Comment by terenceli** [comment]
> @terenceli
> 
> TCG are all compiled out from binaries, including x86 and ARM.
Any plan to remove the code from source tree?

**Comment by terenceli** [comment]
> @terenceli
> 
> TCG are all compiled out from binaries, including x86 and ARM.


Any plan to remove the code from source tree

**Comment by yangzhon** [comment]
@terenceli

TCG is still useful for other customers, we don't need remove this code in upstream QEMU.

NEMU make those features configurable and one shell script will remove those code according to CONFIGs in ./tools/build*.sh and target.mk file.

Please ref https://github.com/intel/nemu/commit/5f2220bbefb81885bbe7111dd51a6e6a0f54f595

**Comment by terenceli** [comment]
@yangzhon 
What's the considerations for leaving the TCG configurable instead remove in nemu? 
I think it is not useful in this project.

**Comment by yangzhon** [comment]
@terenceli

All NEMU patches will be upstreamed into QEMU.

**Comment by rbradford** [comment]
@terenceli the https://github.com/intel/nemu/tree/experiment/automatic-removal branch has the all the code that we don't build removed and it supports only virt (x86 and arm)

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
