### ISSUE TITLE
virtio support for i386/virt

### ISSUE THREAD

**Issue by sameo** [intel/nemu#16]
We want the i386 virt platform to support virtio devices.
As we want to keep the PCI dependency to a minimum, we should aim at exposing virtio devices to the guest through MMIO.

TBD: If we are to support minimal PCI emulation (host bridge+root port), can we go virtio pci instead?

**Comment by liujing2** [comment]
@rbradford @sameo @mcastelino @yangzhon 
I tested virtio-blk-pci and virtio-net-pci hotplugging onto **pcie-root-port** on i386/virt platform and succeed.
Is this what we expected?

Commands:
{ "execute": "device_add", "arguments": { "driver": "virtio-net-pci", "id": "virtio-net1", "bus": "rp1", "bootindex": "2", "addr": "2" } }

{ "execute": "blockdev-add", "arguments":{"driver":"raw","node-name":"disk1", "file":{"driver":"file","filename":"/home/liujing/work/image/null.img" } } }
{ "execute": "device_add", "arguments": { "driver": "virtio-blk", "drive": "disk1", "id": "virtio1", "bus": "rp1", "bootindex": "1", "addr": "1"} }

**Comment by rbradford** [comment]
/CC @sboeuf

I thought Sebastien tried this yesterday and found it didn't work

**Comment by sboeuf** [comment]
@liujing2 what is the rp1 bus ? Is that something that has been introduced with some recent OVMF changes ?

What I did yesterday was:
```bash
sudo ./x86_64-softmmu/qemu-system-x86_64 \
    -bios $HOME/workloads/OVMF.fd \
    -nographic \
    -nodefaults \
    -L . \
    -machine virt,accel=kvm,kernel_irqchip \
    -smp sockets=1,cpus=4,cores=2,maxcpus=8 -cpu host \
    -m 8192M,slots=2,maxmem=16950M \
    -device sysbus-debugcon,iobase=0x402,chardev=debugcon -chardev file,path=/tmp/debug-log,id=debugcon \
    -device virtio-blk-pci,drive=image -drive if=none,id=image,file=$HOME/workloads/clear-24250-cloud.img \
    -device virtio-serial-pci,id=virtio-serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev stdio,id=charconsole0 \
    -netdev user,id=mynet0,hostfwd=tcp::${VMN}0022-:22,hostfwd=tcp::${VMN}2375-:2375 -device virtio-net-pci,netdev=mynet0 \
    -monitor telnet:127.0.0.1:55555,server,nowait \
    -qmp unix:/run/virtcontainers/pods/wH9OFIZOLD5jtSs3PNht/monitor.sock,server,nowait
```
And from a separate shell:
```bash
sudo socat - unix-connect:/run/virtcontainers/pods/wH9OFIZOLD5jtSs3PNht/monitor.sock
{ "execute": "qmp_capabilities" }
{"return": {}}
{ "execute": "blockdev-add", "arguments":{"driver":"raw","node-name":"disk1", "file":{"driver":"file","filename":"/dev/dm-1" } } }
{"return": {}}
{ "execute": "device_add", "arguments": { "driver": "virtio-blk", "drive": "disk1", "id": "virtio1", "bus": "pcie.0","addr": "3", "bootindex": "1" } }
{"error": {"class": "GenericError", "desc": "Bus 'pcie.0' does not support hotplugging"}}
```

Now, if I try `"bus": "rp1"`, I get a different error because it does not even know about this bus:
```
{ "execute": "device_add", "arguments": { "driver": "virtio-blk", "drive": "disk1", "id": "virtio1", "bus": "rp1","addr": "1", "bootindex": "1" } }
{"error": {"class": "GenericError", "desc": "Bus 'rp1' not found"}}

```

**Comment by liujing2** [comment]
@sboeuf The pcie.0 does not support hot-plug in theory, so we need test the virtio hotplug on pcie-root-port, whose id is "rp1" in my test. Sorry to mention that yesterday.

**Comment by liujing2** [comment]
@sboeuf  I add -device pcie-root-port,id=rp1,addr=6,bus=pcie.0 \ into the commands.

**Comment by liujing2** [comment]
@sameo @rbradford @sboeuf @mcastelino  
Update the status:
virtio hotplugging works only on direct kernel boot, fails for OVMF boot. I am still looking at this.

**Comment by liujing2** [comment]
This is the guest dmesg for direct kernel booting.
I am not sure if we could ignore the last message because we use MSI?
root@kata-container ~ # [  604.939696] pciehp 0000:00:06.0:pcie004: Slot(0): Attention button pressed
[  604.939953] pciehp 0000:00:06.0:pcie004: Slot(0): Card present
[  604.940176] pciehp 0000:00:06.0:pcie004: Slot(0) Powering on due to button press
[  606.090183] pci 0000:01:00.0: BAR 4: assigned [mem 0x100000000-0x100003fff 64bit pref]
[  606.090554] pci 0000:01:00.0: BAR 1: assigned [mem 0x90000000-0x90000fff]
[  606.090758] pcieport 0000:00:06.0: PCI bridge to [bus 01]
[  606.090930] pcieport 0000:00:06.0:   bridge window [io  0x1000-0x1fff]
[  606.093710] pcieport 0000:00:06.0:   bridge window [mem 0x90000000-0x901fffff]
[  606.095129] pcieport 0000:00:06.0:   bridge window [mem 0x100000000-0x1001fffff 64bit pref]
[  606.096464] virtio-pci 0000:01:00.0: enabling device (0000 -> 0002)
**[  606.097098] pcieport 0000:00:06.0: can't derive routing for PCI INT A
[  606.097193] virtio-pci 0000:01:00.0: PCI INT A: no GSI**

**Comment by liujing2** [comment]
@rbradford @sboeuf @mcastelino 
1. The latest cloud image [clear-24330-cloud.img](https://download.clearlinux.org/releases/24330/clear/clear-24330-cloud.img.xz ) uses 4.17.14-272.kvm (uname -a).  I downloaded the corresponding [src.rpm](https://download.clearlinux.org/releases/current/clear/source/SRPMS/linux-kvm-4.17.14-272.src.rpm) and [rpm](https://download.clearlinux.org/releases/24330/clear/x86_64/os/Packages/linux-kvm-4.17.14-272.x86_64.rpm) to get the config file and source code, finding it doesn't include the PCI hotplug related config. So I think we need add these into our cloud img.
2. Met many problems when trying to copy the src.rpm and rpm into cloud.img to replace the guest kernel. The cloud.img only has ~500M can be used and even doesn't have "rpm" command. @sboeuf How do you do that?

**Comment by liujing2** [comment]
For PCIe hotplug in guest:
CONFIG_HOTPLUG_PCI=y
CONFIG_HOTPLUG_PCI_PCIE=y
CONFIG_PCIEAER=y
CONFIG_PCIEASPM=y
CONFIG_PCIEASPM_DEFAULT=y

**Comment by sboeuf** [comment]
@liujing2 
>Met many problems when trying to copy the src.rpm and rpm into cloud.img to replace the guest kernel. The cloud.img only has ~500M can be used and even doesn't have "rpm" command. @sboeuf How do you do that?

You should get the rpm on your local machine and extract it to a directory. Once extracted, you should mount the CL cloud image and replace both the kernel and the modules. Here is a list of steps that you can use:
```
$ rpm2cpio linux-kvm-4.17.14-273.x86_64.rpm | cpio -idmv
$ wget https://download.clearlinux.org/releases/24250/clear/clear-24250-cloud.img.xz
$ unxz clear-24250-cloud.img
$ mkdir mount_img
$ sudo guestmount -a clear-24250-cloud.img -m /dev/sda1 mount_img/
$ sudo su
# cd mount_img/loader
# echo "default Clear-linux-kvm-4.17.14-273" > loader.conf
# cd entries
# echo "title Clear Linux OS for Intel Architecture \
linux /EFI/org.clearlinux/kernel-org.clearlinux.kvm.4.17.14-273 \
options root=PARTUUID=c626aa28-69b2-4c30-9982-f61bd4e993da console=hvc0 console=hvc1 init=/usr/lib/systemd/systemd-bootchart initcall_debug tsc=reliable no_timer_check noreplace-smp cryptomgr.notests rootfstype=ext4,btrfs,xfs kvm-intel.nested=1 rw" >Clear-linux-kvm-4.17.14-273.conf
# cd ../../EFI/org.clearlinux/
# cp ../../../usr/lib/kernel/org.clearlinux.kvm.4.17.14-273 kernel-org.clearlinux.kvm.4.17.14-273
# cd ../../..
# exit
$ sudo guestunmount mount_img/
$ sudo guestmount -a clear-24250-cloud.img -m /dev/sda2 mount_img/
$ sudo su
# cd mount_dir/usr/lib/modules/
# cp -R ../../../../usr/lib/modules/4.17.14-273.kvm .
# cd -
# exit
$ sudo guestunmount mount_img/
```

Let me know if something's not clear ;)

**Comment by sboeuf** [comment]
@liujing2 
Today, I have tried to hotplug some virtio-...-pci devices but nothing happened inside the VM. Using the pcie root port `rp1` that I have added from the qemu command line works, and from the monitor, I can "add" some devices. But from inside the VM, nothing happens, nothing is created.
I have tried this on the direct kernel boot since the CL image does not have all the kernel configs needed.

Could you tell me what you did to validate the devices were properly showing up inside the VM ?

And also, could you share your whole kernel config when you got this working ?

**Comment by liujing2** [comment]
@sboeuf Firstly thanks for the details and I need convert from qcow2 to raw then mount. :)
For the directly kernel boot, I evaluated today that my guest can hotplug. Copy the whole config as follows.
```
#
# Automatically generated file; DO NOT EDIT.
# Linux/x86 4.14.22 Kernel Configuration
#
CONFIG_64BIT=y
CONFIG_X86_64=y
CONFIG_X86=y
CONFIG_INSTRUCTION_DECODER=y
CONFIG_OUTPUT_FORMAT="elf64-x86-64"
CONFIG_ARCH_DEFCONFIG="arch/x86/configs/x86_64_defconfig"
CONFIG_LOCKDEP_SUPPORT=y
CONFIG_STACKTRACE_SUPPORT=y
CONFIG_MMU=y
CONFIG_ARCH_MMAP_RND_BITS_MIN=28
CONFIG_ARCH_MMAP_RND_BITS_MAX=32
CONFIG_ARCH_MMAP_RND_COMPAT_BITS_MIN=8
CONFIG_ARCH_MMAP_RND_COMPAT_BITS_MAX=16
CONFIG_NEED_DMA_MAP_STATE=y
CONFIG_NEED_SG_DMA_LENGTH=y
CONFIG_GENERIC_BUG=y
CONFIG_GENERIC_BUG_RELATIVE_POINTERS=y
CONFIG_GENERIC_HWEIGHT=y
CONFIG_RWSEM_XCHGADD_ALGORITHM=y
CONFIG_GENERIC_CALIBRATE_DELAY=y
CONFIG_ARCH_HAS_CPU_RELAX=y
CONFIG_ARCH_HAS_CACHE_LINE_SIZE=y
CONFIG_HAVE_SETUP_PER_CPU_AREA=y
CONFIG_NEED_PER_CPU_EMBED_FIRST_CHUNK=y
CONFIG_NEED_PER_CPU_PAGE_FIRST_CHUNK=y
CONFIG_ARCH_HIBERNATION_POSSIBLE=y
CONFIG_ARCH_SUSPEND_POSSIBLE=y
CONFIG_ARCH_WANT_HUGE_PMD_SHARE=y
CONFIG_ARCH_WANT_GENERAL_HUGETLB=y
CONFIG_ZONE_DMA32=y
CONFIG_AUDIT_ARCH=y
CONFIG_ARCH_SUPPORTS_OPTIMIZED_INLINING=y
CONFIG_ARCH_SUPPORTS_DEBUG_PAGEALLOC=y
CONFIG_HAVE_INTEL_TXT=y
CONFIG_X86_64_SMP=y
CONFIG_ARCH_SUPPORTS_UPROBES=y
CONFIG_FIX_EARLYCON_MEM=y
CONFIG_PGTABLE_LEVELS=4
CONFIG_DEFCONFIG_LIST="/lib/modules/$UNAME_RELEASE/.config"
CONFIG_IRQ_WORK=y
CONFIG_BUILDTIME_EXTABLE_SORT=y
CONFIG_THREAD_INFO_IN_TASK=y
#
# Bus options (PCI etc.)
#
CONFIG_PCI=y
CONFIG_PCI_DIRECT=y
CONFIG_PCI_MMCONFIG=y
CONFIG_PCI_DOMAINS=y
CONFIG_MMCONF_FAM10H=y
# CONFIG_PCI_CNB20LE_QUIRK is not set
CONFIG_PCIEPORTBUS=y
CONFIG_HOTPLUG_PCI_PCIE=y
CONFIG_PCIEAER=y
# CONFIG_PCIE_ECRC is not set
# CONFIG_PCIEAER_INJECT is not set
CONFIG_PCIEASPM=y
# CONFIG_PCIEASPM_DEBUG is not set
CONFIG_PCIEASPM_DEFAULT=y
# CONFIG_PCIEASPM_POWERSAVE is not set
# CONFIG_PCIEASPM_POWER_SUPERSAVE is not set
# CONFIG_PCIEASPM_PERFORMANCE is not set
CONFIG_PCIE_PME=y
# CONFIG_PCIE_DPC is not set
# CONFIG_PCIE_PTM is not set
CONFIG_PCI_BUS_ADDR_T_64BIT=y
CONFIG_PCI_MSI=y
CONFIG_PCI_MSI_IRQ_DOMAIN=y
CONFIG_PCI_QUIRKS=y
# CONFIG_PCI_DEBUG is not set
# CONFIG_PCI_REALLOC_ENABLE_AUTO is not set
# CONFIG_PCI_STUB is not set
CONFIG_PCI_ATS=y
CONFIG_PCI_LOCKLESS_CONFIG=y
CONFIG_PCI_IOV=y
# CONFIG_PCI_PRI is not set
# CONFIG_PCI_PASID is not set
CONFIG_PCI_LABEL=y
CONFIG_HOTPLUG_PCI=y
CONFIG_HOTPLUG_PCI_ACPI=y
# CONFIG_HOTPLUG_PCI_ACPI_IBM is not set
# CONFIG_HOTPLUG_PCI_CPCI is not set
CONFIG_HOTPLUG_PCI_SHPC=y
#
# Virtio drivers
#
CONFIG_VIRTIO_PCI=y
CONFIG_VIRTIO_PCI_LEGACY=y
CONFIG_VIRTIO_BALLOON=y
```
And this is my qemu commands:
```
sudo /home/liujing/work/code/nemu/x86_64-softmmu/qemu-system-x86_64 \
        -nographic -nodefaults -L . \
        -machine virt,accel=kvm,kernel_irqchip,nofw -cpu host -m 512  \
        -smp sockets=1,cpus=4,cores=2,maxcpus=8 \
        -kernel /home/liujing/work/image/src/linux-4.17.14/vmlinux  \
        -append 'root=/dev/vda2 rw rootfstype=ext4 data=ordered rcupdate.rcu_expedited=1 pci=lastbus=0 tsc=reliable no_timer_check noapictimer console=hvc0' \
         -device virtio-blk-pci,drive=image -drive if=none,id=image,aio=threads,file=/home/liujing/work/image/clear-24330-cloud.img \
        -device virtio-serial-pci,id=virtio-serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev stdio,id=charconsole0 \
        -monitor telnet:127.0.0.1:5000,server,nowait \
        -device pcie-root-port,id=rp1,addr=6,bus=pcie.0,multifunction=on \
        -qmp unix:hypervisor.sock,server,nowait \
```
I pasted the PCI related part. And you could ping me directly if anything I missed.

**Comment by sboeuf** [comment]
Thanks @liujing2 ! I'll give this a try!

**Comment by sboeuf** [comment]
@liujing2 I don't know why it does not work for me...

Just to clarify, after you hotplug any virtio-blk-pci or virtio-net-pci, you get a new entry when you look at `/sys/bus/pci/devices`, right ?

@rbradford @sameo could you try this on your machine ? The QMP command to add the new PCI device works, but it does not appear (not detected) by the guest kernel...

**Comment by sboeuf** [comment]
@liujing2 this worked for me eventually !
Either using this:
```
{ "execute": "device_add", "arguments": { "driver": "virtio-net-pci", "id": "virtio-net1", "bus": "rp1"} }
```
or:
```
(qemu) device_add virtio-net-pci,bus=rp1
```

**Comment by liujing2** [comment]
@sboeuf Good to know that!!

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
