### ISSUE TITLE
The Q35 and PC machine type can not work in x86 binary with NEMU repo 

### ISSUE THREAD

**Issue by yangzhon** [intel/nemu#160]
@sameo @rbradford 

When i did build-x86_64 build, and i found q35 or pc machine type could not work with qemu-system-x86_64 binary, did you face this issue ?

**Comment by rbradford** [comment]
Define "could not work" we run NATS with pc and q35 as part of our CI. What are you doing that causes it to fail?

**Comment by yangzhon** [comment]
@rbradford 

I used my previous q35 qemu command and found it failed in boot the VM
./qemu-system-x86_64 -machine pc -enable-kvm  -cpu host -m 1024,maxmem=20G,slots=2 -smp 6 -kernel /home/chen/project/bug-debug/linux-stable/arch/x86/boot/bzImage -append 'root=/dev/vda3 rw rootfstype=ext4 data=ordered rcupdate.rcu_expedited=1 pci=lastbus=0 pci=realloc=on tsc=reliable no_timer_check reboot=t noapictimer console=hvc0' -no-user-config -nodefaults -drive file=/home/chen/project/clear-18080-kvm.img,if=virtio,format=raw -nographic -device virtio-serial-pci,id=virtio-serial0,disable-modern -chardev stdio,id=charconsole0 -device virtconsole,chardev=charconsole0,id=console -monitor telnet:127.0.0.1:55555,server,nowait

**Comment by rbradford** [comment]
@yangzhon our CI system now tests PC + Q35 with direct kernel booting and it works fine. Can you describe how it fails to work?

**Comment by yangzhon** [comment]
@rbradford ，

Thanks for comments, and i used the latest NEMU code and above command to try again, the pc and q35 can normally work in x86 build. thanks, i will close this issue.
