### ISSUE TITLE
few questions about the firmware boot time

### ISSUE THREAD

**Issue by gssxd** [intel/nemu#168]
1, Based on my testing result, the UEFI OVMF boot seems a little bit slow(~delay 800ms) that compared with seaBIOS, which is the default BIOS of QEMU. Have you done any tunning for OVMF fast boot or any plan for future? 
2, I noticed the qboot is very fast, but it just support to boot into linux kernel?   As for the linux distributions, do we have one fast boot FW to support?
3,seaBIOS does support the UEFI CSM. Why don't we enable the seaBIOS as the deafult firmware? any concern?

**Comment by rbradford** [comment]
Investigating a port of Seabios is something we're certainly looking into.

**Comment by gssxd** [comment]
> Investigating a port of Seabios is something we're certainly looking into.

@rbradford So, your decision is to port Seabios instead of OVMF.   Did you have any chance to optimize OVMF startup time?

**Comment by gssxd** [comment]
I have few years FW develop experience(including legace BIOS and UEFI), not an expert.... But I am pretty interested in the firmware part. Maybe I could contribute a little bit on the investigation or some other works.

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
