### ISSUE TITLE
the size of nemu code

### ISSUE THREAD

**Issue by gssxd** [intel/nemu#169]
In the README, it says that nemu will reduce the size of code. then I did the statistics of nemu code and found that the LOC of nemu seems larger than qemu code.  On developer perspective, I dont see any benifit, we still need to read large size of code. Any plan to do more work for reducing the size of nemu code？

**Comment by rbradford** [comment]
Please see our branch where we automatically publish our reduced code: https://github.com/intel/nemu/tree/experiment/automatic-removal
