### ISSUE TITLE
Investigate Seabios

### ISSUE THREAD

**Issue by rbradford** [intel/nemu#171]
At KVM forum I received some feedback that it might be possible to configure/modify Seabios to produce a faster boot than OVMF, particularly when doing direct kernel boot.

Here is an interesting and relevant (if a little old) thread:

https://mail.coreboot.org/pipermail/seabios/2015-July/009497.html

**Comment by sboeuf** [comment]
Yes interesting thread (ppl arguing is always funny :p). And here is the most interesting part for us: https://mail.coreboot.org/pipermail/seabios/2015-July/009508.html

**Comment by sameo** [comment]
QEMU follow up:
https://lists.gnu.org/archive/html/qemu-devel/2018-11/msg03330.html

**Comment by sboeuf** [comment]
Oh pretty cool to see that someone's looking into this.
@rbradford did you sync with Stefano about this?

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
