### ISSUE TITLE
nats: CPUHotplug with virt is failing ~90% of time

### ISSUE THREAD

**Issue by rbradford** [intel/nemu#174]
This is a github issue to track fixing this as it will be temporarily disabled to get the tree running green again.

**Comment by sboeuf** [comment]
@rbradford Could you post the logs from the failing runs regarding CPU hotplug? It'd be helpful to start debugging this issue.

**Comment by rbradford** [comment]
It's hard to debug with NATS. But so far i'm seeing that when the command:

```sudo sh -c "echo 1 > /sys/devices/system/cpu/cpu2/online"``` is run it never exits and the SSH connection times out. Future SSH connections give connection refused.

Here was the command line:

```
        nemu_test.go:183: launching /home/rob/build-x86_64/x86_64-softmmu/qemu-system-x86_64 with: [-machine virt,accel=kvm,kernel_irqchip,nvdimm -bios /home/rob/workloads/OVMF.fd -smp 2,cores=1,threads=1,sockets=2,maxcpus=32 -m 512,slots=4,maxmem=16384M -cpu host -nographic -no-user-config -nodefaults -drive file=/tmp/nemu-test731220262,if=none,id=drive-virtio-disk0,format=qcow2 -device virtio-blk-pci,scsi=off,drive=drive-virtio-disk0,id=virtio-disk0 -device virtio-blk-pci,drive=cloud -drive if=none,id=cloud,file=/tmp/nemu-test192399437,format=raw -netdev user,id=mynet0,hostfwd=tcp::2222-:22,hostname=nemuvm -device virtio-net-pci,netdev=mynet0 -device virtio-serial-pci,id=virtio-serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev file,id=charconsole0,path=/tmp/nemu-test936231971,server,nowait -device virtio-rng-pci,rng=rng0 -object rng-random,filename=/dev/random,id=rng0 -device virtio-balloon-pci -object cryptodev-backend-builtin,id=cryptodev0 -device virtio-crypto-pci,id=crypto0,cryptodev=cryptodev0 -device sysbus-debugcon,iobase=0x402,chardev=debugcon -chardev file,path=/tmp/nemu-test630099209,id=debugcon -device sysbus-debugcon,iobase=0x3f8,chardev=serialcon -chardev file,path=/tmp/nemu-test274485460,id=serialcon -kernel /home/rob/workloads/org.clearlinux.kvm.4.18.16-293 -append root=/dev/vda2 rw console=hvc0 -qmp unix:/tmp/nemu-test284851016,server,nowait]

```

It's important to note this test works fine with Q35 and pc.

**Comment by sboeuf** [comment]
@rbradford the weird part in this is the fact that it's working sometimes. I'll try on my machine.

**Comment by sboeuf** [comment]
@rbradford 
I have tried several things today, but with no luck so far... Here is what I did:
- Because I saw the builds where failing only from today, and older builds were not failing (from 13 days ago), I thought there might be a relation with the fact that the new OVMF binary (v0.6) got released 13 days ago. Unfortunately, it didn't help since I still got some failing builds on PR #175 
- Looking at all the failing builds, not only the CPU hotplug for `virt` was failing. I have seen some failures for ACPICheckTables for `virt` and some failures for `pc` too. That's why I thought it was something more random and that it was related to the entropy of the VM. Because SSH consumes entropy and because the CI runs in a VM already, I thought that by running out of entropy, the VM might be slower sometimes. I have replaced `/dev/random` (blocking) with `/dev/urandom` (non-blocking) for `virtio-rng`, but again no luck. (see #176) 

One last point I haven't investigated but that might be worth looking at is TSC and RTC potential issues:

I have noticed that `rtc_cmos` was failing. I know we don't have a cmos, but is this failure expected?
```
            [    1.112802] genirq: Flags mismatch irq 8. 00000080 (rtc0) vs. 00000000 (virtio2-config)
            [    1.112990] CPU: 1 PID: 1 Comm: swapper/0 Not tainted 4.18.16-293.kvm #2
            [    1.113089] Call Trace:
            [    1.113089]  dump_stack+0x5c/0x90
            [    1.113089]  __setup_irq.cold.8+0x4e/0xaa
            [    1.113089]  ? dev_set_name+0x42/0x60
            [    1.113089]  request_threaded_irq+0xef/0x160
            [    1.113089]  cmos_do_probe+0x27a/0x460
            [    1.113089]  platform_drv_probe+0x33/0x90
            [    1.113089]  driver_probe_device+0x223/0x440
            [    1.113089]  __driver_attach+0xe0/0x110
            [    1.113089]  ? driver_probe_device+0x440/0x440
            [    1.113089]  bus_for_each_dev+0x64/0xa0
            [    1.113089]  bus_add_driver+0x153/0x230
            [    1.113089]  driver_register+0x66/0xb3
            [    1.113089]  __platform_driver_probe+0x58/0xe0
            [    1.113089]  ? do_early_param+0x8d/0x8d
            [    1.113089]  cmos_init+0x39/0x6b
            [    1.113089]  ? rtc_dev_init+0x35/0x35
            [    1.113089]  do_one_initcall+0x42/0x178
            [    1.113089]  ? do_early_param+0x8d/0x8d
            [    1.113089]  kernel_init_freeable+0x159/0x1e8
            [    1.113089]  ? rest_init+0x95/0x95
            [    1.113089]  kernel_init+0x5/0xf9
            [    1.115170]  ret_from_fork+0x35/0x40
            [    1.115300] rtc_cmos: probe of rtc_cmos failed with error -16
```

Also, on my machine, using the exact same image `clear-25950-cloud.img` and the same kernel `org.clearlinux.kvm.4.18.16-293` led me to a slight difference about the logs I got from the kernel when adding CPU2:

My logs:
```
[   33.919603] smpboot: Booting Node 0 Processor 2 APIC 0x2
[   33.919494] kvm-clock: cpu 2, msr 0:1ff20081, secondary cpu clock
[   33.939932] KVM setup async PF for cpu 2
[   33.940507] kvm-stealtime: cpu 2, msr 1f714f40
[   33.941534] Will online and init hotplugged CPU: 2
```

vs the CI logs:

```
[   25.411846] smpboot: Booting Node 0 Processor 2 APIC 0x2
[   25.387998] kvm-clock: cpu 2, msr 0:1ff20081, secondary cpu clock
[   25.414981] TSC ADJUST compensate: CPU2 observed -1002 warp. Adjust: -1002
[   25.456292] KVM setup async PF for cpu 2
[   25.456724] kvm-stealtime: cpu 2, msr 1e094f40
[   25.459226] Will online and init hotplugged CPU: 2
```

the diff being:
```
[   25.414981] TSC ADJUST compensate: CPU2 observed -1002 warp. Adjust: -1002
```

Here are some thoughts, I hope you can continue debugging this...

**Comment by rbradford** [comment]
@sboeuf good debugging work. Some comments

> Looking at all the failing builds, not only the CPU hotplug for virt was failing. I have seen some failures for ACPICheckTables for virt and some failures for pc too. 

The errors related to the ACPI test are related to the use of "shutdown -h now" and inappropriate timeouts there https://github.com/intel/nemu/commit/38a4f3d3536539a3bafd13d3408bdcfbe06011b3 .

If you look at https://nemu-jenkins-ci.westus2.cloudapp.azure.com/job/nemu/job/topic%252Fvirt-x86/ the 2 hourly builds I ran overnight show pretty consistent pass rates now that the ACPI test is fixed. So that is a bit of a misdirection.

> Because SSH consumes entropy and because the CI runs in a VM already, I thought that by running out of entropy, the VM might be slower sometimes. I have replaced /dev/random (blocking) with /dev/urandom (non-blocking) for virtio-rng, but again no luck. (see #176)

Is a good thought. However with the CPU test the first SSH in (to get the list of CPUs that are currently online) succeeds. It's only after we try and enable the recently added CPU does the guest system appear to hang and stop responding.

> [   25.414981] TSC ADJUST compensate: CPU2 observed -1002 warp. Adjust: -1002

Is very interesting and the difference could be related to the CPU model of the host (or in the Azure case the L1 VM)

My next step is to try and reproduce without using NATS and to try and get any kernel output from the hang by connecting an interactive shell.

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
