### ISSUE TITLE
libvirt support

### ISSUE THREAD

**Issue by mnaser** [intel/nemu#185]
Hi there,

This is a pretty exciting projects and I'm trying to see if we can add coverage to get OpenStack running/tested on top of it.  However, OpenStack deploys VMs using `libvirt`.  Is there a recommended or documented way of using `nemu` with libvirt?  Can we just drop in the file?

Thanks,
Mohammed

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
