### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mnaser** [intel/nemu#186]
Hi there,

I don't see any specific documentation on building the project and getting started with it.  Am I not finding it?  Do we need to work on tracking how to get it in there?

Thanks,
Mohammed

**Comment by rbradford** [comment]
Our wiki has the documentation we have so far: https://github.com/intel/nemu/wiki/Running-NEMU

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
