### ISSUE TITLE
automatic-removal branch compile failed

### ISSUE THREAD

**Issue by caoruidong** [intel/nemu#190]
I encounter some compile error
```
  CC      crypto/tlssession.o
  CC      crypto/secret.o
make: *** No rule to make target `crypto/random-platform.o', needed by `scsi/qemu-pr-helper'.  Stop.
make: *** Waiting for unfinished jobs....
```
I'm on a CentOS machine. What's your compile environment? Or where can I get the binary directly?

**Comment by caoruidong** [comment]
Seems gcc is too old. Update to 7.2.1 solved.

**Comment by rbradford** [comment]
For the experiment/automatic-removal branch you must compile with `tools/build_x86_64_virt.sh` or `tools/build_aarch64.sh` as files not used by those builds will be deleted from the tree but not removed from the Makefiles.

**Comment by caoruidong** [comment]
Yes, I use tools/build_x86_64_virt.sh, it failed.

**Comment by rbradford** [comment]
Please could you create a gist with the full build output including the output from configure and i'll look into it.

**Comment by caoruidong** [comment]
Here https://gist.github.com/caoruidong/b3e55814a08bbcaacb6a620f860bd369 Thanks! I think it is because of configure option.

**Comment by rbradford** [comment]
I made some progress with #194 but I ran into some build problems which I think might be related to the very old gcc (4.8) that you get on Centos 7:

```
In file included from /home/rob/nemu/exec.c:26:0:
/home/rob/nemu/include/exec/tcg-wrapper.h:61:33: error: no previous prototype for ‘page_collection_lock’ [-Werror=missing-prototypes]
 inline struct page_collection * page_collection_lock(tb_page_addr_t start, tb_page_addr_t end)
                                 ^
/home/rob/nemu/include/exec/tcg-wrapper.h:66:13: error: no previous prototype for ‘page_collection_unlock’ [-Werror=missing-prototypes]
 inline void page_collection_unlock(struct page_collection *set)
             ^
/home/rob/nemu/include/exec/tcg-wrapper.h:88:13: error: no previous prototype for ‘tb_flush’ [-Werror=missing-prototypes]
 inline void tb_flush(CPUState *cpu)
             ^
/home/rob/nemu/include/exec/tcg-wrapper.h:92:13: error: no previous prototype for ‘tlb_set_dirty’ [-Werror=missing-prototypes]
 inline void tlb_set_dirty(CPUState *cpu, target_ulong vaddr)
             ^
/home/rob/nemu/include/exec/tcg-wrapper.h:104:13: error: no previous prototype for ‘tcg_register_thread’ [-Werror=missing-prototypes]
 inline void tcg_register_thread(void)
             ^
/home/rob/nemu/include/exec/tcg-wrapper.h:108:13: error: no previous prototype for ‘tcg_region_init’ [-Werror=missing-prototypes]
 inline void tcg_region_init(void)

```

If you `-Wno-error` the warnings away you get link issues instead. I didn't think that inline functions in the header file need a prototype.

**Comment by caoruidong** [comment]
I have installed the new version of GCC 7.2 and these warnings are gone. Compare to release, some configs about crypto is the reason. Thanks @rbradford https://github.com/intel/nemu/pull/194 fixes a part. I add --disable-gcrypt additionally and it compiles successfully.
