### ISSUE TITLE
Guest Variable CPU Clock Support under -cpu host

### ISSUE THREAD

**Issue by dakami** [intel/nemu#200]
Running Nemu on an Up Squared board, I note that the guest is unaware of the clock speed of the host.  The board scales from 1.1ghz to 2.3ghz, so it's not a trivial perf differential.  The host *might* still be scaling the processor anyway, but the guest (at least under Windows 10) doesn't know, and may not be scheduling appropriately.

Thanks for taking a crack at better hardware virtualization!

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
