### ISSUE TITLE
what's the difference between nemu and qemu-lite

### ISSUE THREAD

**Issue by gssxd** [intel/nemu#201]
Both are Intel's light-weight VM solution, and based on qemu, what's the difference?

**Comment by yangzhon** [comment]
@gssxd 

Let me explain this difference to you
QEMU-LITE is skip-bios solution to speedup VM boottime and memory footprint, this solution will directly boot ELF guest kernel from qemu and skip seabios ---> decompressed kernel---> protected kernel.  Currently Qqemu-lite can support PC and Q35 machine type.

NEMU is only for modern cloud usage, and we created one new machine type, virt, which is only support PCIe hostbridge, so we can remove lots of unused emulation devices, this project mainly focused on security.

**Comment by gssxd** [comment]
@yangzhon
Thanks for your reply.
I noticed kata 1.4 release decleared NEMU as a new feature.
Does that mean NEMU will replace QEMU-lite as the default hypervior of kata?

**Comment by yangzhon** [comment]
@gssxd

NEMU is also as one device model option for KATA container.

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
