### ISSUE TITLE
How to support windows guest for nume？

### ISSUE THREAD

**Issue by adofirst2018** [intel/nemu#202]
@sameo  We test geust windows7 on nemu, But we find nemu can not run windows7 guest,
I have some questions:
1、	do you have a plan to support windows guest for nemu? 
2、	We want to support windows guest for nemu, can you give me some advice? 
thanks

**Comment by rbradford** [comment]
We have not validated any version of Windows against NEMU.

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
