### ISSUE TITLE
NEMU boot latency time in seabios is longer than qemu

### ISSUE THREAD

**Issue by Wong-Jing** [intel/nemu#203]
**Qemu**
My test qemu version is 2.8.1, with rel-1.10.2 seaBIOS, qemu command line is:

> qemu-system-x86_64 -machine pc-i440fx-2.8 -enable-kvm -cpu host -name debug-threads=on -kernel kernel_benchmark -initrd initrd.img -realtime mlock=off -no-user-config -nodefaults -no-reboot -rtc base=utc,clock=vm,driftfix=slew -display none -boot strict=on -m size=64,slots=1,maxmem=131073M -smp cpus=1,maxcpus=64 -numa node,nodeid=0,cpus=0-63,mem=64 -pidfile /var/run/pidfile -bios /home/qemu-seabios.bin -device isa-debug-exit,iobase=0xf5,iosize=0x4 -qmp unix:/var/run/qmp.sock,server,nowait -serial unix:/var/run/console.sock,server,nowait -device virtio-serial-pci,id=virtio-serial0 -chardev socket,id=charch0,path=/var/run/hyper.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charch0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charch1,path=/var/run/tty.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charch1,id=channel1,name=sh.hyper.channel.1 -append 'console=ttyS0 panic=1 no_timer_check pci=nocrs'

**Test result:**
Loop 10 times

qemu_init_end:isa-debug-exit,iobase=0xf5, 
real    0m0.538s
user    0m0.334s
sys     0m0.207s

fw_do_boot:isa-debug-exit,iobase=0xf6
real    0m0.860s
user    0m0.468s
sys     0m0.404s

**Nemu**
Nemu is the latest version, with latest seaBIOS from https://github.com/rbradford/seabios.git ,nemu command line is:

> qemu-system-x86_64_virt -machine virt,accel=kvm,kernel_irqchip -enable-kvm -cpu host -name debug-threads=on -kernel kernel_benchmark -initrd initrd.img -realtime mlock=off -no-user-config -nodefaults -no-reboot -rtc base=utc,clock=vm,driftfix=slew -display none -boot strict=on -m size=64,slots=1,maxmem=131073M -smp cpus=1,maxcpus=64 -numa node,nodeid=0,cpus=0-63,mem=64 -pidfile /var/run/pidfile -bios /home/bios.bin -device sysbus-debugexit,iobase=0xf5,iosize=0x4 -L /home/pc-bios/optionrom/ -qmp unix:/var/run/qmp.sock,server,nowait -serial unix:/var/run/console.sock,server,nowait -device virtio-serial-pci,id=virtio-serial0 -chardev socket,id=charch0,path=/var/run/hyper.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charch0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charch1,path=/var/run/tty.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charch1,id=channel1,name=sh.hyper.channel.1 -append 'console=ttyS0 panic=1 no_timer_check pci=nocrs'

**Test result:**
Loop 10 times

qemu_init_end:sysbus-debugexit.iobase=0xf5
real    0m0.366s
user    0m0.148s
sys     0m0.173s

fw_do_boot:sysbus-debugexit.iobase=0xf6
real    0m1.369s
user    0m0.672s
sys     0m0.639s

Applied this patch to seaBIOS for measuring boot latency.
```
diff --git a/src/post.c b/src/post.c
index f93106a..ce2bd5a 100644
--- a/src/post.c
+++ b/src/post.c
@@ -320,6 +320,7 @@ dopost(void)
 void VISIBLE32FLAT
 handle_post(void)
 {
+    outb(1, 0xf5); //Measuring Boot Latency
     if (!CONFIG_QEMU && !CONFIG_COREBOOT)
         return;

diff --git a/src/stacks.c b/src/stacks.c
index 2fe1bfb..0a52301 100644
--- a/src/stacks.c
+++ b/src/stacks.c
@@ -415,6 +415,7 @@ _farcall16(struct bregs *callregs, u16 callregseg)
         return;
     }
     ASSERT16();
+    outb(1, 0xf6); //Measuring Boot Latency
     asm volatile(
         "calll __farcall16\n"
         : "+a" (callregs), "+m" (*callregs), "+d" (callregseg)

```
Dose it feel right? IMO, nemu should be faster.

**Comment by yangzhon** [comment]
@rbradford ,

Did you check this issue before ?  This issue is caused by Seabios ?  thanks!

**Comment by yangzhon** [comment]
@Wong-Jing 

Please check below test, thanks!
https://lists.gnu.org/archive/html/qemu-devel/2018-12/msg00200.html

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
