### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by c0d3z3r0** [intel/nemu#204]
Hi, can you add a short description of the branches to the wiki, please? It's a bit unclear to me :(
How is experimental/automatic-removal generated?
What is realeses/candidate? The release-branch?

**Comment by yangzhon** [comment]
The release is topic/virt-x86 branch, and experimental/automatic-removal is generated by one script to remove some unused code with configs in virt platform.

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
