### ISSUE TITLE
Rebase on QEMU 4.0

### ISSUE THREAD

**Issue by sboeuf** [intel/nemu#206]
QEMU 4.0 release is around the corner, and is planned to be released on April 16th. We should make sure that NEMU will be rebased on top of this new release.

/cc @rbradford @sameo @yangzhon

**Comment by rbradford** [comment]
@sboeuf The next QEMU release is 4.0. Here is the detailed timeline: https://wiki.qemu.org/Planning/4.0

**Comment by yangzhon** [comment]
We had better rebase on QEMU 4.0, in that time, Kconfig has been merged into QEMU 4.0 and @sameo will talk with Paolo in PTG about NEMU upstream.

**Comment by sboeuf** [comment]
@rbradford oh yes thanks for fixing this :)

**Comment by yangzhon** [comment]
@sameo 

I rebased 47 patches, which include 3 new patches, please help me review my new patches, thanks!
https://github.com/yangzhon/nemu/commits/topic/virt-x86-4.0-rc0

#nemu porting patch history
##. removed patch list 
1)0007-target-arm-Move-all-VFP-helpers-into-their-own-file.patch
   old commit id: 49b422837af2eb27845fbf56acca432249d57f1c
   reason: there is one vfp_helper.c in target/arm of QEMU4.0
(2)0046-hw-arm-Switch-to-the-AML-build-RSDP-building-routine.patch
   old commit id: 1759f04f6fbe88f7a29c536f0a06bfe58a4eb87d
   reason: build_rsdp() has been moved to aml-build.c in QEMU4.0

##. new patch added list
(1)0030: i386: virt refactor load_linux with conf struct
   commit id: 764c7e5aef1dd5ca4399dc7fa73d6652d010d4b4 
   reason: PVH support
(2)0035: i386: refactor sysfw.c for all platforms
   commit id: 4e7316dbdd8c03f13040d9f19a5f5288cb826fe8
   reason: change sysfw.c for all platform
(3)0036: i386: virt: add flash support in virt platform
   commit id: d620641f201a803a63bd283b4841d95860e0c7de
   reason: pflash support in virt platform

Notice:  I only did build test and did not do real image load test.

**Comment by egernst** [comment]
@sboeuf @yangzhon  - I believe there are updates here?

**Comment by sboeuf** [comment]
Yes, NEMU has been rebased onto 4.0-rc4 and has been merged into the branch `topic/virt-x86-v4.0-rc4`. We cannot merge it to the official NEMU branch `topic/virt-x86` yet because QEMU 4.0 is not out yet.

**Comment by sboeuf** [comment]
We can close this issue now! The rebase onto QEMU 4.0 is complete and part of `topic/virt-x86` branch.
