### ISSUE TITLE
Missing PCI routing table support

### ISSUE THREAD

**Issue by sboeuf** [intel/nemu#207]
Ok so today @rbradford and myself were investigating the reason why NEMU was not supporting the virtio-rng device properly. The driver probing fails because of this:
```
[    0.254121] virtio_rng: probe of virtio1 failed with error -107
```
Following this lead, @rbradford found out that IRQs were not properly assigned to our virtio devices:
```
root@clr ~ # lspci -vvv
00:00.0 Host bridge: Red Hat, Inc. QEMU PCIe Host bridge
        Subsystem: Red Hat, Inc. Device 1100
    ...

00:01.0 Communication controller: Red Hat, Inc. Virtio console
        Subsystem: Red Hat, Inc. Device 0003
    ...
        Interrupt: pin A routed to IRQ -2147483648
    ...

00:02.0 Unclassified device [00ff]: Red Hat, Inc. Virtio RNG
        Subsystem: Red Hat, Inc. Device 0004
    ...
        Interrupt: pin A routed to IRQ -2147483648
    ...
```
So by looking into our ACPI tables, we realized there was no PCI routing table (_PRT) exposed through ACPI, related to our PCI device, and there were no `LNK` devices defined either.

Our understanding so far is that usually a _PRT method is invoked to retrieve the interrupt from the _PRS, and leave the choice to the guest OS to pick one of the proposed values. Once the guest picked, it sends the information back to the VMM through _SRS method evaluation.

@yangzhon @chao-p @liujing2 if I'm not mistaken, we're using the qemu-lite PCI host bridge emulation in NEMU, and this should come with the associated `_PRT` in the ACPI tables, right?

It'd be nice if someone could you take a look at it and provide some patches.

/cc @mcastelino @sameo @rbradford

**Comment by yangzhon** [comment]
@sboeuf ，

Yes, we didn't  add _PRT acpi before.  

We will look at this issue when we rebase the NEMU based on QEMU4.0.

**Comment by sboeuf** [comment]
@yangzhon shouldn't we start solving this issue right now? This is independent from the 4.0 patches, and it is a lack of support for `virt`.

@sameo wdyt?

**Comment by rbradford** [comment]
@sboeuf I've made a bit of progress. I tracked the issue down to the virtio-rng device being the only device where `pci_msix_vec_count` generates an error because `pci->msi_cap` is zero.

All other devices successfully get through the MSI setup. Because it fails the MSI based setup it falls through to legacy interrupt handling which also fails and generates the error we see:

```
        /* Try MSI-X with one vector per queue. */
	err = vp_find_vqs_msix(vdev, nvqs, vqs, callbacks, names, true, ctx, desc);
	if (!err)
		return 0;
	/* Fallback: MSI-X with one vector for config, one shared for queues. */
	err = vp_find_vqs_msix(vdev, nvqs, vqs, callbacks, names, false, ctx, desc);
	if (!err)
		return 0;
	/* Finally fall back to regular interrupts. */
	return vp_find_vqs_intx(vdev, nvqs, vqs, callbacks, names, ctx);
```

All other devices succeed in one of the first two paths. But virtio-rng falls into the last one. I'm currently debugging why that is. We really should be able to enter through the former.

**Comment by sboeuf** [comment]
@rbradford thanks for the update. And IIUC, because we don't have the PRT support, it also fails in the last path, right?
I agree the issue should be solved at the root of the problem, which means the first path using MSI-X should work.

I'm wondering if we still want the PRT support to be implemented? What does it buy us if we are sure that MSI-X is supported everywhere?

**Comment by rbradford** [comment]
@sboeuf  fix in #208 if you're interested.

**Comment by sboeuf** [comment]
Thank you @rbradford, it LGTM :)

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
