### ISSUE TITLE
add virtio-fs support

### ISSUE THREAD

**Issue by egernst** [intel/nemu#211]
depends on #206

**Comment by sboeuf** [comment]
Once NEMU will be rebased on top of 4.0-rc0, we need two things:
- Submit a PR to apply virtio-fs patches
- Submit a PR to build and publish `virtiofsd` from the CI

**Comment by egernst** [comment]
any updates? @sboeuf @yangzhon - I believe there are updates here?


Who should be assigned this issue?

**Comment by sboeuf** [comment]
@egernst I have assigned this issue to myself.
Yes there are updates, the PR #217 is currently being tested and we will generate both NEMU and virtiofsd binaries from this to be consumed by Kata.

You can move forward with modifying the Kata NEMU CI job in order to pull both binaries.

**Comment by sboeuf** [comment]
Early release binaries published here: https://github.com/intel/nemu/releases/tag/nemu-virtio-fs-1

But we still want to wait for the proper QEMU 4.0 release cut before to make everything final.

**Comment by sboeuf** [comment]
`virtio-fs` patches are now part of NEMU 4.0, we can close this issue.
