### ISSUE TITLE
NATS: Add virtio-fs testing

### ISSUE THREAD

**Issue by sboeuf** [intel/nemu#226]
Now that #225 has been merged, NEMU 4.0 is capable of `virtio-fs` (or `vhost-user-fs-pci` to be precise) support.
In order to prevent regression issues regarding this feature, we need to write some tests to validate that it always works.

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
