### ISSUE TITLE
HVM direct boot

### ISSUE THREAD

**Issue by wkozaczuk** [intel/nemu#228]
As I understand NEMU has just been recently rebased against QEMU 4.0 and it should now support "HVM direct boot" (is PVH same thing?) - https://patchwork.kernel.org/patch/10741013/. Am I correct? I believe there are two relevant branches - virt-x86-v4.0-rc4 and virt-x86-4.0.0 - which one should I use?

In order to boot Linux using this method I need an uncompressed vmlinux 64-bit ELF image. Is this correct? Or it needs to be properly compiled so it needs to be a special version of it? If it is a special version, could you please point me to the specific instance of kernel you tested with? 

Does this boot method work with any firmware? If special one could you please point me to a file that works?

Lastly do you have an example of invoking NEMU with proper parameters to boot this way (-boot, -kernel, etc)?

Thanks in advance,
Waldek

**Comment by stefano-garzarella** [comment]
Hi @wkozaczuk,
I wrote some notes on how to use "HVM direct boot" (yes, we called also PVH) with QEMU 4.0 and I guess it's similar in NEMU:
https://gist.github.com/stefano-garzarella/7b7e17e75add20abd1c42fb496cc6504

> As I understand NEMU has just been recently rebased against QEMU 4.0 and it should now support "HVM direct boot" (is PVH same thing?) - https://patchwork.kernel.org/patch/10741013/. Am I correct? I believe there are two relevant branches - virt-x86-v4.0-rc4 and virt-x86-4.0.0 - which one should I use?
> 
> In order to boot Linux using this method I need an uncompressed vmlinux 64-bit ELF image. Is this correct? Or it needs to be properly compiled so it needs to be a special version of it? If it is a special version, could you please point me to the specific instance of kernel you tested with?

Yes, you need the vmlinux 64-bit ELF image and you have to enable CONFIG_PVH in the Linux configuration.

> Does this boot method work with any firmware? If special one could you please point me to a file that works?

It works with the standard (SeaBIOS) firmware or with qboot.

> Lastly do you have an example of invoking NEMU with proper parameters to boot this way (-boot, -kernel, etc)?

I put an example in the notes.

I hope it helps,
Stefano

**Comment by wkozaczuk** [comment]
@stefano-garzarella Thanks for the info. I have eventually found some time to enhance OSv to support HVM boot. I have tested it with QEMU 4.0.50 (built from source). Here is a command line:
```
qemu-system-x86_64 \
 -m 64M -smp 1 \
 -nodefaults \
 -append '--bootchart /hello' \
 -machine q35,accel=kvm,kernel_irqchip \
 -kernel ./loader.elf \
 -vga none -display none \
 -serial mon:stdio \
 -device virtio-blk-pci,id=blk0,drive=hd0,scsi=off \
 -drive file=./usr.img,if=none,id=hd0,cache=none,aio=threads
``` 

On another hand, I cannot get OSv to HVM-boot on Nemu. I tried this command line:
```
qemu-system-x86_64_virt -L ./bioses \
 -m 512M -smp 1 \
 -device sysbus-debugcon,iobase=0x402,chardev=debugcon \
 -chardev file,path=/tmp/debug-log,id=debugcon \
 -device sysbus-debugcon,iobase=0x3f8,chardev=serialcon \
 -chardev file,path=/tmp/serial-log,id=serialcon \
 -nodefaults \
 -append 'root=/dev/vda console=ttyS0' \
 -machine virt,accel=kvm,kernel_irqchip \
 -kernel ./loader.elf \
 -vga none -display none \
 -serial mon:stdio \
 -device virtio-blk-pci,id=blk0,drive=hd0,scsi=off \
 -drive file=./usr.img,if=none,id=hd0,cache=none,aio=threads
``` 
and I get this (nemu does not actually boot OSv):
```
QEMU 4.0.0 monitor - type 'help' for more information
(qemu) 
```

The ./bioses directory has these:
```
bios.bin
pvh.bin
```

The debug log shows this:
```
SeaBIOS (version rel-1.12.0-26-g6e56ed1)
BUILD: gcc: (Ubuntu 8.3.0-6ubuntu1) 8.3.0 binutils: (GNU Binutils for Ubuntu) 2.32
No Xen hypervisor found.
Unable to unlock ram - bridge not found
Running on QEMU (unknown nb: 8086:0d57)
Running on KVM
RamSize: 0x00ff0000 [cmos]
Relocating init from 0x000e57c0 to 0x00fa17c0 (size 59296)
Found QEMU fw_cfg
QEMU fw_cfg DMA interface supported
RamBlock: addr 0x0000000000000000 len 0x0000000020000000 [e820]
Moving pm_base to 0x600
boot order:
1: /rom@genroms/linuxboot_dma.bin
=== PCI bus & bridge init ===
PCI: pci_bios_init_bus_rec bus = 0x0
=== PCI device probing ===
Found 2 PCI devices (max PCI bus is 00)
=== PCI new allocation pass #1 ===
PCI: check devices
=== PCI new allocation pass #2 ===
PCI: IO: c000 - c07f
PCI: 32: 0000000000ff0000 - 00000000fec00000
PCI: map device bdf=00:01.0  bar 0, addr 0000c000, size 00000080 [io]
PCI: map device bdf=00:01.0  bar 1, addr febff000, size 00001000 [mem]
PCI: map device bdf=00:01.0  bar 4, addr febf8000, size 00004000 [prefmem]
PCI: init bdf=00:00.0 id=8086:0d57
PCI: init bdf=00:01.0 id=1af4:1001
pci_slot_get_irq called with unknown routing
PCI: No VGA devices found
```

I have been using the NEMU binary of the latest release published on github.

What am I doing wrong?

Lastly, I saw the timing numbers around PVH boot with seabios and qboot. There does not seem to be much difference in favor or qboot which I thought was supposed to much faster.

**Comment by stefano-garzarella** [comment]
> @stefano-garzarella Thanks for the info. I have eventually found some time to enhance OSv to support HVM boot. I have tested it with QEMU 4.0.50 (built from source). Here is a command line:

Great! :)

> On another hand, I cannot get OSv to HVM-boot on Nemu. I tried this command line:
> The debug log shows this:
> 
> ```
> SeaBIOS (version rel-1.12.0-26-g6e56ed1)
> BUILD: gcc: (Ubuntu 8.3.0-6ubuntu1) 8.3.0 binutils: (GNU Binutils for Ubuntu) 2.32
> No Xen hypervisor found.
> Unable to unlock ram - bridge not found
> Running on QEMU (unknown nb: 8086:0d57)
> Running on KVM
> RamSize: 0x00ff0000 [cmos]
> Relocating init from 0x000e57c0 to 0x00fa17c0 (size 59296)
> Found QEMU fw_cfg
> QEMU fw_cfg DMA interface supported
> RamBlock: addr 0x0000000000000000 len 0x0000000020000000 [e820]
> Moving pm_base to 0x600
> boot order:
> 1: /rom@genroms/linuxboot_dma.bin

This line is strange because I would expect pvh.bin here.

> I have been using the NEMU binary of the latest release published on github.
> 
> What am I doing wrong?

I don't know. I never tried NEMU + PVH. Maybe @yangzhon tried it and he can help.
> 
> Lastly, I saw the timing numbers around PVH boot with seabios and qboot. There does not seem to be much difference in favor or qboot which I thought was supposed to much faster.

I agree. SeaBIOS + PVH optionrom is not so bad.

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
