### ISSUE TITLE
When was Intel Nemu project started ?

### ISSUE THREAD

**Issue by Wenzel** [intel/nemu#237]
Hi,

I'm maintaing a list of resources regarding virtualization on Github:
https://github.com/Wenzel/awesome-virtualization

And i wanted to add `nemu` to the project's list.
However, i can't figure when the project started. (the projects are listed in a timeline)

Looking at the logs with `git log --reverse`, the first commit dates back in 2003... ?
![Screenshot_20190720_011058](https://user-images.githubusercontent.com/964610/61570172-479a9580-aa8b-11e9-9da4-5ca9f5201f5f.png)

Since you know better than me about this, can you tell me the date, or even better, make a PR ? :)

Thanks !

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
