### ISSUE TITLE
PCI hotplug through ACPI

### ISSUE THREAD

**Issue by sboeuf** [intel/nemu#53]
We need to investigate how much it costs (from an emulation standpoint) to enable PCI hotplug through ACPI for `virt`.
This will help to make some comparison with other potential options and how much we can save with those options.

**Comment by sboeuf** [comment]
@liujing2 I have just created the branch `topic/virt-x86_pcihp_acpi` for the purpose of PCI hotplug through ACPI support.
We can use it to share the code.

**Comment by liujing2** [comment]
@sboeuf @mcastelino 
What is our "goal bus" for PCI hotplug? pcie-root-port or pcie.0 or others?

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
