### ISSUE TITLE
The bzImage loading is failed in pc/xen/q35 platfrom

### ISSUE THREAD

**Issue by yangzhon** [intel/nemu#54]
@sameo, @rbradford 
Since we added the new struct AcpiConfiguration for acpi usage, which is initialized latterly in pc_machine_done() and some member in AcpiConfiguration are not initialized, which made the qemu coredump while loading bzImage.

by the way, for xen, which is using pc machine type and will call xen_load_linux(pcms), in this time. the  AcpiConfiguration  should not be initialized.

So, we need refractor this struct and related load_linux_bzimage() functions.

**Comment by sameo** [comment]
This is fixed on topic/virt-x86-3.0
@yangzhon Could you please test again?

**Comment by yangzhon** [comment]
@sameo ,

I have successfully verified bzImage loading test on Q35/PC platform, thanks!
