### ISSUE TITLE
specify -kernel not working on cpu/mem hotplug

### ISSUE THREAD

**Issue by liujing2** [intel/nemu#70]
Hi all,
When I add -kernel rpmsrc/linux-4.17.14/arch/x86/boot/bzImage and tested cpu/memory hotplug, it fails with no kernel message.
Downloaded [linux-kvm-4.17.14-274.src.rpm](https://download.clearlinux.org/releases/24690/clear/source/SRPMS/linux-kvm-4.17.14-274.src.rpm) , which includes config and source codes. 
I checked the config w/ CONFIG_ACPI_HOTPLUG_CPU=y, CONFIG_HOTPLUG_CPU=y and CONFIG_ACPI_HOTPLUG_MEMORY=y, CONFIG_MEMORY_HOTPLUG=y.

I don't have any idea for now.
@rbradford @mcastelino @sameo  @yangzhon

**Comment by sameo** [comment]
Does hot plug and hot removal both fail?

**Comment by liujing2** [comment]
kernel 4.16, [config](https://gist.github.com/liujing2/f867abdf00015e5a7c0c4b986e2bd52d), need add CONFIG_MEMORY_HOTPLUG_DEFAULT_ONLINE=y, or online by manual, memory hotplug succeeds.  hot remove memory is the same as #71 
cpu hotplug/unplug works too.
Double checked the 4.17.14-274 kernel config and it includes all needed config. Don't know what else configuration needed?

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
