### ISSUE TITLE
Missing NATS tests for object properties

### ISSUE THREAD

**Issue by sameo** [intel/nemu#87]
We are missing NATS tests for verifying that we are carrying the right driver/object default properties.
For example we want to make sure that the `apic-common` `vapic` property is always turned off but we're not testing this.

Ideally this should be done in 2 steps:

* [ ] Add an object property getter API to govmm
* [ ] Define an array of (object, property, value) tuples to be checked from NATS

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
