### ISSUE TITLE
NEMU run some error

### ISSUE THREAD

**Issue by adofirst2018** [intel/nemu#94]
I try start NEMU follow this command， but  faced some error.

[root@duhy nemu]# qemu-system-x86_64 -m 2048M -smp 4 -drive file=qemu-3.0.qcow2,cache=none,if=virtio -machine virt,accel=kvm,kernel_irqchip -net nic -net tap,ifname=tap0,script=no,downscript=no
**
ERROR:qom/object.c:542:object_new_with_type: assertion failed: (type != NULL)
Aborted (core dumped)

[root@duhy nemu]# qemu-system-x86_64 -machine help
Supported machines are:
....
virt                 QEMU 3.0 i386 Virtual Machine (alias of virt-3.0)
virt-3.0             QEMU 3.0 i386 Virtual Machine
virt-2.12            QEMU 2.12 i386 Virtual Machine
isapc                ISA-only PC
none                 empty machine

**Comment by adofirst2018** [comment]
(gdb) bt
#0  0x00007fffed82a277 in raise () at /lib64/libc.so.6
#1  0x00007fffed82b968 in abort () at /lib64/libc.so.6
#2  0x00007ffff74e00c5 in g_assertion_message () at /lib64/libglib-2.0.so.0
#3  0x00007ffff74e015a in g_assertion_message_expr () at /lib64/libglib-2.0.so.0
#4  0x0000555555cad188 in object_new_with_type (type=0x0) at qom/object.c:542
#5  0x0000555555cad200 in object_new (typename=0x0) at qom/object.c:556
#6  0x0000555555925a62 in cpu_new (typename=0x0, apic_id=0, errp=0x555556808cd8 <error_fatal>)
    at /home/duhy/workSpace/nemu/qemu/hw/i386/cpu.c:38
#7  0x00005555559261db in cpus_init (ms=0x55555691ba60, compat=false) at /home/duhy/workSpace/nemu/qemu/hw/i386/cpu.c:170
#8  0x00005555559527ac in virt_machine_state_init (machine=0x55555691ba60) at /home/duhy/workSpace/nemu/qemu/hw/i386/virt/virt.c:217
#9  0x0000555555aa316d in machine_run_board_init (machine=0x55555691ba60) at hw/core/machine.c:830
#10 0x00005555559e9593 in main (argc=13, argv=0x7fffffffe3a8, envp=0x7fffffffe418) at vl.c:4516

**Comment by rbradford** [comment]
@duhongyu This won't happen if you add -cpu host

**Comment by adofirst2018** [comment]
> @duhongyu This won't happen if you add -cpu host

thanks

**Comment by adofirst2018** [comment]
I start NEMU follow this command:
`qemu-system-x86_64 \
        -machine virt,accel=kvm,kernel_irqchip -cpu host \
        -m size=1G,slots=2,maxmem=3G \
        -smp sockets=1,cpus=4,cores=2,maxcpus=8 \
        -device virtio-blk-pci,drive=image -drive if=none,id=image,file=qemu-3.0.qcow2 \
        -device virtio-serial-pci,id=virtio-serial0 \
        -device virtconsole,chardev=charconsole0,id=console0 \
        -chardev stdio,id=charconsole0 \
        -monitor telnet:127.0.0.1:5000,server,nowait`
my host is x86 centos7.4 , guest is centos7.4. but can not start NEMU
![image](https://user-images.githubusercontent.com/6764115/45826098-5064f280-bd26-11e8-8830-48cb44d6f7b4.png)

**Comment by rbradford** [comment]
Unless you have a custom CentOS image that uses EFI you cannot use that with NEMU. You need to use a distribution with cloud images that uses EFI: Ubuntu or Clear Linux are the most popular options.

**Comment by rbradford** [comment]
Here are some details: https://gist.github.com/rbradford/b816fb153174fa2feff1edb3f92de2b7

**Comment by adofirst2018** [comment]
> Here are some details: https://gist.github.com/rbradford/b816fb153174fa2feff1edb3f92de2b7

but I must run centos7.4 by NEMU， how to  fixed centos or bios， can you give me some info?

**Comment by rbradford** [comment]
Closing this issue as you opened #99 in its place.
