### ISSUE TITLE
How to run centos in NEMU?

### ISSUE THREAD

**Issue by adofirst2018** [intel/nemu#99]
I want to run centos in NEMU, how to custom centos image?

**Comment by rbradford** [comment]
You cannot use the CentOS cloud images as they do not support EFI. However you can install into a virtual disk using the Q35 machine type and it's fully working serial port and the stock installer. It's not well documented how to do a serial install but i've figured it out and written instructions below:

To use CentOS download the minimal installer: 

```wget http://mirror.mhd.uk.as44574.net/mirror.centos.org/7.5.1804/isos/x86_64/CentOS-7-x86_64-Minimal-1804.iso```

Run NEMU/QEMU with Q35 machine type and a serial console for the install:

```
dd if=/dev/zero of=diskvm.img bs=8M count=1024
~/build-x86_64/x86_64-softmmu/qemu-system-x86_64 -bios ~/workloads/OVMF.fd -nographic -nodefaults -L . -net none -machine q35,accel=kvm,kernel_irqchip -cpu host -m 4096,slots=4,maxmem=16950M -smp 2  -chardev file,path=/tmp/debug-log,id=debugcon -device virtio-blk-pci,drive=disk -drive if=none,id=disk,file=diskvm.img -serial stdio -netdev user,id=mynet0,hostfwd=tcp::2222-:22,hostname=nemuvm -device virtio-net-pci,netdev=mynet0 -device virtio-blk-pci,drive=iso -drive if=none,id=iso,file=$HOME/Downloads/CentOS-7-x86_64-Minimal-1804.iso
```

This will drop you into EFI shell. Launch the installer with:
```
FS1:
cd EFI
cd BOOT
BOOTX64.EFI 
```

On the "Install CentOS" option, press e to edit

Delete `quiet` and replace with `console=ttyS0 console=hvc0 inst.text`

Make sure you put `console=hvc0` as the last console option. This will then be copied into the disk image as the grub default.

Press `ctrl-x` to boot

Go through text mode installer to install to the disk.  After the installer reboots, do not boot with current QEMU command line as you will not get any output as the default console is different. You can then use the virt command line:

```
~/build-x86_64/x86_64-softmmu/qemu-system-x86_64 -bios ~/workloads/OVMF.fd -nographic -nodefaults -L . -net none -machine virt,accel=kvm,kernel_irqchip -m 4096,slots=4,maxmem=16950M -smp 2 -device sysbus-debugcon,iobase=0x402,chardev=debugcon -chardev file,path=/tmp/debug-log,id=debugcon -device sysbus-debugcon,iobase=0x3f8,chardev=serialcon -chardev file,path=/tmp/serial-log,id=serialcon -device virtio-blk-pci,drive=disk -drive if=none,id=disk,file=diskvm.img -device virtio-serial-pci,id=virtio-serial0  -device virtconsole,chardev=charconsole0,id=console0 -chardev stdio,id=charconsole0 -netdev user,id=mynet0,hostfwd=tcp::2222-:22,hostname=nemuvm -device virtio-net-pci,netdev=mynet0
```

This will result in a working CentOS image running with NEMU and the "virt" machine type.

**Comment by adofirst2018** [comment]
@rbradford thanks for your response.

**Comment by adofirst2018** [comment]
@rbradford   I try run centos with nemu follow your guidance，but here is some error in debug-log

[Security] 3rd party image[0] can be loaded after EndOfDxe: PciRoot(0x0)/Pci(0x1,0x0)/HD(1,GPT,22FE2257-A9FE-40C3-AEFF-A9CAC97234D2,0x800,0x64000)/\EFI\BOOT\BOOTX64.EFI.
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 7E6DF140
Loading driver at 0x0007E470000 EntryPoint=0x0007E48C000 
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 7F2A9718
ProtectUefiImageCommon - 0x7E6DF140
  - 0x000000007E470000 - 0x0000000000127000
Error: Image at 0007E470000 start failed: Not Found
Image Return Status = Not Found
Memory  Previous  Current    Next   
 Type    Pages     Pages     Pages  
======  ========  ========  ========
  0A    00000004  00000003  00000004
  09    00000008  00000008  00000008
  00    00000004  00000003  00000004
  06    00000024  000000C0  000000F0
  05    00000030  0000003E  0000004D
  03    00000180  00000348  0000041A
  04    00000F00  0000120E  00001691
EmuVariablesUpdatedCallback
FSOpen: Open 'NvVars' Success
Saved NV Variables to NvVars file
Memory Type Information settings change.
[Bds]Booting UEFI PXEv4 (MAC:525400123456)
InstallProtocolInterface: 245DCA21-FB7B-11D3-8F01-00A0C969723B 7E7C70E0
PXE: Failed to read system GUID from the smbios table!
MnpAddFreeTxBuf: Add TxBufWrap 7E6C9098, TxBuf 7E6C90C1

**Comment by rbradford** [comment]
@duhongyu  That error is because OVMF could not find a boot loader on the disk. Did you successfully install to the disk image you made?

**Comment by fangying** [comment]
Hi, I am running CentOS with NEMU following the guide [https://github.com/intel/nemu/wiki/NEMU-with-CentOS](url).

I got CentOS installed under EFI and grub2-efi.cfg modified according to your guide. When I tried to launch CentOS with NEMU, I got some msg in /tmp/debug-log and could not launch CentOS with NEMU.

> AcpiTimerLibConstructor: Unknown Host Bridge Device ID: 0x0008
ASSERT /builddir/build/BUILD/edk2-vUDK2018/OvmfPkg/Library/AcpiTimerLib/BaseRomAcpiTimerLib.c(65): ((BOOLEAN)(0==1))

I picked the OVMF.fd from [https://download.clearlinux.org/image/OVMF.fd](url)
Could you please give me some insight here ? @rbradford

**Comment by rbradford** [comment]
@fangying Use this OVMF binary: https://github.com/intel/ovmf-virt/releases/download/0.6/OVMF.fd

**Comment by fangying** [comment]
> @fangying Use this OVMF binary: https://github.com/intel/ovmf-virt/releases/download/0.6/OVMF.fd

Thanks for your help，NEMU works fine with this OVMF.fd, I can launch my CentOS VM now.

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
